name: Build and Deploy Jenkins
on:
  push:
    branches:
      - develop
jobs:
  build:
      name: Build and push new islasgeci/jenkins image
      runs-on: ubuntu-latest
      steps:
      - name: Copia repositorio
        uses: actions/checkout@v2
      - name: Construye imagen
        run: docker build --tag islasgeci/jenkins:latest --tag islasgeci/jenkins:${GITHUB_SHA:0:4} .
      - name: Docker log-in
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
      - name: Sube latest a Docker Hub
        run: docker push islasgeci/jenkins:latest
      - name: Sube sha a Docker Hub
        run: docker push islasgeci/jenkins:${GITHUB_SHA:0:4}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Pull and run islasgeci/jenkins image through ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          docker stop jenkins || true
          docker system prune --all --force --volumes
          docker pull islasgeci/jenkins:latest
          docker run \
          --detach \
          --name jenkins \
          --publish 50000:50000 \
          --publish 8080:8080 \
          --rm \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --volume ${HOME}/.vault/.secrets:/.vault/.secrets \
          --volume jenkins_home:/var/jenkins_home \
          islasgeci/jenkins:latest