name: Manual deploy latest
on: [workflow_dispatch]
jobs:
  deploy:
    name: Manual deploy
    runs-on: ubuntu-latest
    steps:
    - name: Pull and run islasgeci/jenkins image through ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST_IP }}
        username: ${{ secrets.SERVER_USERNAME }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: 22
        script: |
          docker stop jenkins || true
          docker system prune --all --force --volumes
          docker pull islasgeci/jenkins:latest
          docker run \
          --detach \
          --name jenkins \
          --publish 50000:50000 \
          --publish 8080:8080 \
          --rm \
          --volume /var/run/docker.sock:/var/run/docker.sock \
          --volume ${HOME}/.vault/.secrets:/.vault/.secrets \
          --volume jenkins_home:/var/jenkins_home \
          islasgeci/jenkins:latest